# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-25 19:52
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_add-js-commands'),
    ]

    operations = [
        migrations.RunSQL([
            "INSERT INTO commands_javascriptclientcommand (command) VALUES ('storeStorageService.posts.removeAllAsync(); storeStorageService.comments.removeAllAsync(); storeStorageService.categorys.removeAllAsync(); storeStorageService.groups.removeAllAsync(); storeStorageService.users.removeAllAsync();')"
        ])
    ]
