# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_person_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='street_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='person',
            name='street_number',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
