# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170526_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='street_number',
            field=models.PositiveIntegerField(),
        ),
    ]
