# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0005_auto_20170526_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnregisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', localflavor.us.models.PhoneNumberField(blank=True, max_length=20)),
                ('coordinator_invitation', models.BooleanField(default=False)),
                ('invitation_accepted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.InvitationMessage')),
            ],
        ),
    ]
