# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170622_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='street_number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
