# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_person_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='coordinator',
            new_name='is_coordinator',
        ),
    ]
