# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170815_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='date_became_inactive',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
