# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 01:22
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
