# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-17 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_person_telephone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('0', 'none'), ('1', 'email'), ('2', 'text_message')], max_length=1)),
                ('frequency', models.CharField(choices=[('0', 'none'), ('1', 'email'), ('2', 'text_message')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='passwordreset',
            name='user',
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
