# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_loopcreationtokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loopcreationtokens',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoopCreationTokens',
        ),
    ]
