# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0020_auto_20170922_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_loop', models.PositiveIntegerField(default=0)),
                ('nominate_founder', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='frequency',
            field=models.CharField(choices=[('1', 'email'), ('2', 'text_message')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='method',
            field=models.CharField(choices=[('1', 'email'), ('2', 'text_message')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
