# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0021_auto_20170924_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_share_address', models.BooleanField(default=True)),
                ('is_share_email', models.BooleanField(default=True)),
                ('is_share_phone', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='frequency',
            field=models.CharField(choices=[('0', 'none'), ('1', 'weekly'), ('2', 'daily'), ('3', 'immediately')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='method',
            field=models.CharField(choices=[('0', 'none'), ('1', 'email'), ('2', 'text'), ('3', 'text_and_email')], default='0', max_length=1),
        ),
    ]
