# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20171011_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_founder',
            field=models.BooleanField(default=False),
        ),
    ]
