# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 01:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_membership_is_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='date_became_coordinator',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
