# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20180220_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='give_kudos',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
