# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-07 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190107_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
