# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190107_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_daily_summary', models.BooleanField(default=False)),
                ('send_weekly_summary', models.BooleanField(default=False)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_preferences', to='users.Membership')),
            ],
        ),
    ]
