# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-09 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def switch_membership_to_usergroup(apps, schema_editor):
    Membership = apps.get_model('users', 'Membership')
    SummaryPreferences = apps.get_model('users', 'SummaryPreferences')

    for prefs in SummaryPreferences.objects.all():
        membership = prefs.membership_id
        mem_user = Membership.objects.get(pk=membership).user
        mem_group = Membership.objects.get(pk=membership).group
        prefs.user = mem_user
        prefs.group = mem_group
        prefs.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0031_fill_summary_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarypreferences',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_preferences', to='auth.Group'),
        ),

        migrations.AddField(
            model_name='summarypreferences',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_preferences', to=settings.AUTH_USER_MODEL),
        ),

        migrations.RunPython(switch_membership_to_usergroup),

        migrations.AlterField(
            model_name='summarypreferences',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_preferences', to='auth.Group'),
        ),

        migrations.AlterField(
            model_name='summarypreferences',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_preferences', to=settings.AUTH_USER_MODEL),
        ),

        migrations.RemoveField(
            model_name='summarypreferences',
            name='membership',
        ),

        migrations.AlterUniqueTogether(
            name='summarypreferences',
            unique_together=set([('user', 'group')]),
        ),
    ]
