# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-09 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_usergroup_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarypreferences',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_preferences', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='summarypreferences',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
