# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-13 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_summaryprefs_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='street_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
