# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-20 20:15
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_street-name-nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='newest_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
