# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def fill_table_defaults(apps, schema_editor):
    Membership = apps.get_model('users', 'Membership')
    SummaryPreferences = apps.get_model('users', 'SummaryPreferences')

    for membership in Membership.objects.all():
      if not SummaryPreferences.objects.filter(user=membership.user, group=membership.group).exists():
        SummaryPreferences.objects.create(
          send_daily_summary = False,
          send_weekly_summary = False, 
          user = membership.user,
          group = membership.group
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_street-name-nullable'),
    ]

    operations = [
        migrations.RunPython(fill_table_defaults)
    ]


