# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-28 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_adddd-newst-update-to-person'),
        ('users', '0035_refill_summary_prefs'),
    ]

    operations = [
    ]
