# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-13 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0038_in-place-membership-removal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToursTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_tour_date', models.DateTimeField(blank=True, null=True)),
                ('post_editor_tour_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tours_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunSQL([("INSERT INTO users_tourstaken (user_id) SELECT id from auth_user")])
    ]
