# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-19 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_add_tours_taken_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferences',
            name='notify_by_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='summarypreferences',
            name='send_weekly_summary',
            field=models.BooleanField(default=True),
        ),
    ]
