# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-22 18:50
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20190319_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
