# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-24 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20190322_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
