# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_add_bio_to_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarypreferences',
            name='send_daily_summary',
            field=models.BooleanField(default=True),
        ),
    ]
