# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-15 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_user-engagement-section'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='can_create_loops',
            field=models.BooleanField(default=False),
        ),
    ]
