# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-15 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_add-create-loop-flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profile_photo',
        ),
    ]
