# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itk_invitations', '0014_auto_20170728_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeepInContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_comments', models.TextField(blank=True)),
                ('loop_description', models.TextField(blank=True)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itk_invitations.UnregisteredUser')),
            ],
        ),
    ]
