cards = {
    # Need to add cards for 'index', 'places' and 'tags'
    'about_loopla' : {
        'card_index' : '1',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-orange',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : 'Welcome to Loopla',
        'subtitle' : 'Learn how it works',
        'body' : 'Select About Loopla from the MORE menu',
    },
    'submit_post' : {
        'card_index' : '2',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-teal-lt',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : "You've got questions",
        'subtitle' : 'Your friends have answers',
        'body' : 'Ask for recommendations, reviews or advice...about anything',
     },
    'submit_comment' : {
        'card_index' : '3',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-pink-lt',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : 'Share your expertise',
        'subtitle' : "Your friends trust your opinion",
        'body' : "Reply to their questions",
     },
    'submit_short_list' : {
        'card_index' : '4',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-green',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : 'Add a Short List entry',
        'subtitle' : "Share the services, businesses and places you recommend",
        'body' : 'Select SHORT LIST from the menu',
     },
     'give_kudos' : {
        'card_index' : '5',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-orange',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : "Thank your friends for helpful contributions",
        'subtitle' : "Give kudos by clicking the circle icon on a post, comment or short list entry",
        'body' : "You have 20 kudos available. More will be available for purchase soon."
    },
#    'give_kudos' : {
#        'card_index' : '5',
#        'card_type' : 'dashboard/special_card_no_modal_01.html',
#        'card_color' : 'background-orange',
#        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
#        'image_height' : '125',
#        'image_width' : '97',
#        'card_title' : 'Send Kudos',
#        'subtitle' : "Thank your friends for helpful contributions",
#        'body' : 'Click Kudos under the ••• menu',
#    },
    'no_advertising' : {
        'card_index' : '10-2',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-teal-lt',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : "No advertising",
        'subtitle' : "Loopla does not share your data or allow advertising",
        'body' : 'Loopla is supported by users sending Kudos to each other. Learn more by clicking About Loopla under the MORE menu.',
     },
    'submit_feedback' : {
        'card_index' : '6',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-pink-lt',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : 'Send us feedback',
        'subtitle' : "What do you like about Loopla? What can be improved?",
        'body' : 'Click on the FEEDBACK button on the left margin of your screen',
     },
    'editable_contributions' : {
        'card_index' : '7',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-green',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : 'Posts and comments are editable',
#        'subtitle' : "We've made it easy to correct typos or fix mistakes",
        'subtitle' : "It's easy to correct typos or fix mistakes",
        #        'body' : "Don't hesitate to ask questions or post comments",
        'body' : "Don't hesitate to post questions and comments",
    },
    'show_post_v2' : {
        'card_index' : '8',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-orange',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : 'View an entire conversation',
        'subtitle' : 'See all the details, including photos, places and tags',
        'body' : "Click on any post on this page",
     },
    'loop_summary' : {
        'card_index' : '9',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-teal-lt',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : 'Learn about your loop',
        'subtitle' : 'View the description, guidelines, admins and members',
        'body' : 'Click on the loop name under the {{ user.first_name }} menu',
     },
     'privacy' : {
        'card_index' : '10',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-pink-lt',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
#        'card_title' : 'Contributions are private',
         'card_title' : 'Loop privacy',
         # 'subtitle' : 'Posts and comments are visible only to members of your loop',
        # 'subtitle' : 'Posts and comments to a loop are visible only to members of the loop',
        'subtitle' : 'Posts and comments to a loop are visible only to loop members',
        'body' : "",
#         'body' : "Loopla does not share or sell your data",
     },
     'be_helpful' : {
        'card_index' : '11',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-green',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : 'Be helpful',
        'subtitle' : 'Write posts that are useful to you and other members of your loop',
        'body' : 'Questions, recommendations, discoveries and DIY solutions make great posts',
     },
     'tight_loop' : {
        'card_index' : '12',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-orange',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : "Keep a tight loop",
#       'card_title' : "We're all friends here",
#       'subtitle' : 'Members of a loop all know each other',
        'subtitle' : 'Limit loop membership to people who know each other',
        # 'body' : 'Have open and comfortable conversations',
        'body' : 'Have open and meaningful conversations',
     },
     'edit_profile_submit' : {
        'card_index' : '13',
        'card_type' : 'dashboard/special_card_no_modal_01.html',
        'card_color' : 'background-pink-lt',
        'monster_image' : 'site_photos/FirstThingMonster_wave_97x125.png',
        'image_height' : '125',
        'image_width' : '97',
        'card_title' : 'Update your profile',
        'subtitle' : 'Add a profile photo and change your settings',
        'body' : 'Click Settings under the {{ user.first_name }} menu',
     },
}
