# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20171107_1924'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0003_auto_20170925_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedCommentToPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedKudosToComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Comment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_sender_comment', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SentKudosToComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='receivedkudostoreply',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='receivedkudostoreply',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='receivedkudostoreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receivedreplytopost',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='receivedreplytopost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sentkudostoreply',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='sentkudostoreply',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReceivedKudosToReply',
        ),
        migrations.DeleteModel(
            name='ReceivedReplyToPost',
        ),
        migrations.DeleteModel(
            name='SentKudosToReply',
        ),
    ]
