# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_shortlist_kudos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0004_auto_20171107_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedKudosToShortList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_sender_short_list', to=settings.AUTH_USER_MODEL)),
                ('short_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ShortList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SentKudosToShortList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('short_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ShortList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
