# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-16 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_simpleaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleaction',
            options={'ordering': ['-date']},
        ),
    ]
