# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('dashboard', '0002_entry_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
