# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170329_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='text',
        ),
    ]
