# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170329_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='summary',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
