# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170329_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='group',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
