# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20170622_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='summary',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
