# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20170628_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
