# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_post_reply_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply_count',
        ),
    ]
