# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_post_reply_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
