# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_groupcategorycount'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupcategorycount',
            name='private_count',
            field=models.IntegerField(default=0),
        ),
    ]
