# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20170903_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='private_reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
