# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0018_post_private_reply_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='kudos',
            field=models.ManyToManyField(related_name='comment_benefactor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='kudos',
            field=models.ManyToManyField(related_name='post_benefactor', to=settings.AUTH_USER_MODEL),
        ),
    ]
