# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-17 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0020_auto_20170912_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('00', 'received_reply_to_post'), ('01', 'received_kudos_to_post'), ('02', 'received_kudos_to_reply'), ('03', 'sent_kudos_to_post'), ('04', 'sent_kudos_to_reply')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Post')),
                ('reply', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
