# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Post'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Comment'),
        ),
    ]
