# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_userevent_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
