# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20171003_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=60)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='post_photos')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Post')),
            ],
        ),
    ]
