# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20171011_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['order_name']},
        ),
        migrations.AddField(
            model_name='label',
            name='order_name',
            field=models.CharField(default='aaa', max_length=3),
        ),
    ]
