# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20171017_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='private_reply_count',
            new_name='private_comment_count',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='reply_count',
            new_name='public_comment_count',
        ),
    ]
