# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_postphoto_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postphoto',
            options={'ordering': ['date_added']},
        ),
    ]
