# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20171201_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlist',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
