# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20171201_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='place',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
