# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-13 16:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20180108_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place_user_generated',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='post',
            name='tags_user_generated',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, null=True, size=None),
        ),
    ]
