# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 17:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20180113_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='place_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='place_user_generated',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='tags_user_generated',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, null=True, size=None),
        ),
    ]
