# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-24 16:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20180114_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='tags_user_generated',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, null=True, size=None),
        ),
    ]
