# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_feedbackfromuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackfromuser',
            name='summary',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='feedbackfromuser',
            name='url',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
