# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0047_auto_20180201_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='kudos',
            field=models.ManyToManyField(related_name='short_list_appreciator', to=settings.AUTH_USER_MODEL),
        ),
    ]
