# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-27 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20180206_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlist',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
