# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-08 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_userdefinedtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_defined_tags',
            field=models.ManyToManyField(to='dashboard.UserDefinedTag'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_defined_tags',
            field=models.ManyToManyField(to='dashboard.UserDefinedTag'),
        ),
        migrations.AddField(
            model_name='shortlist',
            name='user_defined_tags',
            field=models.ManyToManyField(to='dashboard.UserDefinedTag'),
        ),
    ]
