# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-25 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20180308_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_user_generated', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
    ]
