# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-14 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_migrate-user-defined-tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newest_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
