# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-14 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_auto_20190214_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=130),
        ),
    ]
