# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_auto_20190214_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='newest_update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),

        migrations.RunSQL(
            # Re-index the post table
            [("REINDEX TABLE dashboard_post")]
        ),
    ]
