# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-05 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0060_add_post_indexes_for_newest_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='internal_copy',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='is_visible_to_group',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='original',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='original_group',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='original_owner',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
