# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-05 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_update_user_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='photo',
        ),
    ]
