# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-13 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_remove_userfeedback_photo'),
        ('dashboard', '0061_in-place-post-comment-deletion'),
    ]

    operations = [
    ]
