# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-24 14:34
from __future__ import unicode_literals
import json
import copy

from django.db import migrations

# The version of SlateJS that we updated to has deprecated the use of leaf nodes
# in text objects. This function will remove them in favor of a single text property
def process_node(node):
  updated_node = copy.deepcopy(node)

  if updated_node['object'] == 'text' and 'leaves' in updated_node:
    
    leaves = updated_node['leaves']
    text = ''

    if 'marks' not in updated_node:
      updated_node['marks'] = []

    # Concatenate the text
    for leaf in leaves:
      text = text + leaf['text']

      # Collect the marks
      for mark in leaf['marks']:
        updated_node['marks'].append(mark)

    updated_node['text'] = text
    updated_node.pop('leaves', None)

  if 'nodes' in node:
    updated_node['nodes'] = []
    for child in node['nodes']:
      updated_node['nodes'].append(process_node(child))

  return updated_node

def process(thing):
  # if we have a value, process it
  if thing.text_rich_json:
    rich_text_data = json.loads(thing.text_rich_json)
    rich_text_data['document'] = process_node(rich_text_data['document'])
    updated_rich_text_json = json.dumps(rich_text_data)
    if thing.text_rich_json != updated_rich_text_json:
      thing.text_rich_json = updated_rich_text_json
      thing.save()


def update_slate_json(apps, schema_editor):
  Post = apps.get_model('dashboard', 'Post')
  Comment = apps.get_model('dashboard', 'Comment')

  for post in Post.objects.all():
    process(post)

  for comment in Comment.objects.all():
    process(comment)
    


class Migration(migrations.Migration):

  dependencies = [
    ('dashboard', '0066_add-rich-text'),
  ]

  operations = [
    migrations.RunPython(update_slate_json),
  ]
