# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-05 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_slate-json-update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text_rich_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_rich_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
