# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-18 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_make-rich-text-optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='label',
        ),
        migrations.RemoveField(
            model_name='category',
            name='link',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='groupcategorycount',
            name='category',
        ),
        migrations.RemoveField(
            model_name='groupcategorycount',
            name='group',
        ),
        migrations.RemoveField(
            model_name='label',
            name='category_parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='shortlist',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='GroupCategoryCount',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
