# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-16 16:57
from __future__ import unicode_literals
import csv, os
from django.conf import settings
from django.db import migrations


def configure_categories_that_always_show(apps, schema_editor):
  Category = apps.get_model('dashboard', 'Category')

  # Read in categories to show
  file_path = os.path.join(settings.BASE_DIR, 'dashboard/migrations/0073_categories_to_always_show.csv')
  with open(file_path) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    parent_category_name = None
    child_category_name = None

    for row in csv_reader:
      # update the parrent name as needed
      if row[0] and row[0] != '':
        parent_category_name = row[0].lower()
        parent_did_change = True
      else:
        parent_did_change = False
    
      # get the child name
      if row[1] and row[1] != '':
        child_category_name = row[1].lower()
      else:
        child_category_name = None

      try:
        if parent_did_change and parent_category_name and parent_category_name != '':
          category = Category.objects.get(name=parent_category_name, parent=None)
          category.always_show_in_menus = True
          category.save()

        if child_category_name and child_category_name != '':
          category = Category.objects.get(name=child_category_name, parent__name=parent_category_name)
          category.always_show_in_menus = True
          category.save()

      except Exception as e:
        print(e)


class Migration(migrations.Migration):

  dependencies = [
    ('dashboard', '0072_give-posts-categories-based-on-tags'),
  ]

  operations = [
    migrations.RunPython(configure_categories_that_always_show),
  ]
