# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-19 15:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('dashboard', '0072_give-posts-categories-based-on-tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('post_references', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='categories',
            field=models.ManyToManyField(to='dashboard.Category'),
        )
    ]
