# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-19 16:21
from __future__ import unicode_literals

from django.db import migrations


def apply_categories_to_comments(apps, schema_editor):
    Comment = apps.get_model('dashboard', 'Comment')

    for comment in Comment.objects.all():
        comment_needs_update = False
        for tag in comment.tags.all():
            for category in tag.categories.all():
                comment_needs_update = True
                comment.categories.add(category)

        if comment_needs_update:
            comment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_set_categories_that_always_display'),
        ('dashboard', '0073_add_category_statistic_tables_and_comment_categories'),
    ]

    operations = [
        migrations.RunPython(apply_categories_to_comments)
    ]
