# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-22 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_set_categories_that_always_display'),
        ('dashboard', '0075_initialize_category_statistics'),
    ]

    operations = [
    ]
