# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-24 19:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_add-ordering-models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=80)),
                ('photo', models.ImageField(upload_to='')),
                ('kudos_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=80)),
                ('limited_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'kudos',
            },
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='collection',
            field=models.ManyToManyField(blank=True, to='shop.Collection'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='kudos',
            field=models.ManyToManyField(blank=True, to='shop.Kudos'),
        ),
    ]
