# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-08 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_add-catalog-models'),
    ]

    operations = [
        migrations.CreateModel(
            name='KudosAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KudosGiven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500)),
                ('edition_number', models.IntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kudos',
            name='number_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kudosgiven',
            name='kudos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Kudos'),
        ),
        migrations.AddField(
            model_name='kudosgiven',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
        migrations.AddField(
            model_name='kudosgiven',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kudosavailable',
            name='kudos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Kudos'),
        ),
        migrations.AddField(
            model_name='kudosavailable',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
        migrations.AddField(
            model_name='kudosavailable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
