# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-18 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_added_available_and_given_kudos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudosavailable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_available', to=settings.AUTH_USER_MODEL),
        ),
    ]
