# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-22 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190718_1209'),
        ('shop', '0004_auto_20190717_0957'),
    ]

    operations = [
    ]
