# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-23 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_merge_20190722_1407'),
        ('shop', '0005_merge_20190722_1323'),
    ]

    operations = [
    ]
