# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itk_invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='response_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
