# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itk_invitations', '0005_auto_20170713_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
