# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('itk_invitations', '0007_nominationmessage_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator_Nomination',
            fields=[
                ('nomination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itk_invitations.Nomination')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
            ],
            bases=('itk_invitations.nomination',),
        ),
    ]
