# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itk_invitations', '0011_auto_20170725_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='first_visit_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='first_visit_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
