# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itk_invitations', '0013_auto_20170728_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_type',
            field=models.CharField(choices=[('1', 'Become_Group_Member'), ('2', 'Become_Group_Coordinator'), ('3', 'Start_Group_From_User'), ('4', 'Start_Group_From_Unregistered_User')], max_length=1),
        ),
    ]
