# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-16 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itk_invitations', '0014_auto_20170728_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='read_email_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
