# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-09 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itk_invitations', '0017_multi-use-invitation-added'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiuseinvitation',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
