# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-23 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itk_invitations', '0018_multi_use_invitations_visiblity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiuseinvitation',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
