# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='coordinator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
