# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_circle_coordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='coordinator',
        ),
    ]
