# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_circle_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='circle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='circle',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
    ]
