# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20170526_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='description',
            field=models.TextField(),
        ),
    ]
