# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20170526_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos'),
        ),
    ]
