# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_circle_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='guidelines',
            field=models.TextField(blank=True),
        ),
    ]
