# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-13 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('groups', '0008_circle_guidelines'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_change', models.CharField(choices=[('1', 'admin_to_member'), ('2', 'admin_to_inactive'), ('3', 'remove_admin'), ('4', 'member_to_admin'), ('5', 'member_to_inactive'), ('6', 'remove_member'), ('8', 'inactive_to_member'), ('9', 'remove_inactive')], max_length=2)),
                ('note', models.TextField(blank=True)),
                ('is_initiated_by_user', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
