# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-01 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('groups', '0009_statuschange'),
  ]

  operations = [
    migrations.AddField(
      model_name='circle',
      name='name',
      field=models.CharField(default='', max_length=80),
      preserve_default=False,
    ),

    migrations.RunSQL([
      'UPDATE groups_circle SET name=(SELECT auth_group.name FROM auth_group WHERE groups_circle.group_id=auth_group.id)'
    ])  
  ]
