export default {
  ADMIN_TO_MEMBER: 'ADMIN_TO_MEMBER',
  ADMIN_TO_INACTIVE: 'ADMIN_TO_INACTIVE',
  REMOVE_ADMIN: 'REMOVE_ADMIN',
  MEMBER_TO_ADMIN: 'MEMBER_TO_ADMIN',
  MEMBER_TO_INACTIVE: 'MEMBER_TO_INACTIVE',
  REMOVE_MEMBER: 'REMOVE_MEMBER',
  INACTIVE_TO_MEMBER: 'INACTIVE_TO_MEMBER',
  REMOVE_INACTIVE: 'REMOVE_INACTIVE'
};